### PR TITLE
Fixes issue: #55

### PR DESCRIPTION
**Pull request by matiwinnetou**
Change-Id: I8ad448ae06ec2da5ce0b9f7a1e62a676a03146af

### CODE REVIEW

**Comment by cosmolev** [comment]
Please merge this PR ASAP.

**Comment by sergeysimonov** [comment]
Can this be merged or any of two later PRs fixing "URI is not hierarchical" issue?

**Comment by matiwinnetou** [comment]
There are actually three PRs as proposals to fix this issue, I think maintainer has totally different concerns at the moment than helping us resolving those issues.

**Comment by frantuma** [comment]
fixed in #64

**Pull request closed without merging**
