### PR TITLE
Upgrade lib version of playframework from '2.4' to '2.5.1

### PR DESCRIPTION
**Pull request by pikel**
Usage of Source instead of Enumerator as recommended in
https://www.playframework.com/documentation/2.5.x/Migration25

Modifications in the SwaggerPlugin constructor:
We do not inject the application, but to avoid a circular dependency
we inject the environment and the configuration.

In order to not modify swagger-scala-module, I've added in the build.sbt
the jackson-module-scala dependence with the same version as the jackson
version used by play 2.5.1.

### CODE REVIEW

**Comment by dwang1223** [comment]
still has errors!

**Comment by gauravranjan11** [comment]
still has errors. im using https://github.com/swagger-api/swagger-play/tree/master/play-2.4/swagger-play2 for integrating swagger with play 2.5

**Comment by djriffel** [comment]
This seems to work fine for me with both Play 2.5.1 and 2.5.3. I had to make two adjustments to fix a couple things I noticed. 

1) In build.sbt I had to change the "swagger-scala-module" version from "1.0.2-SNAPSHOT" to "1.0.2" (it seems that this version is on release now, and it was not found in any of the snapshot repos that my sbt was searching otherwise).

2) On line 131 in SwaggerPlugin.scala I had to change StaticPart(prefix + "/") to StaticPart(prefix) in order to prevent a double forward-slash prefix on all of my paths (perhaps a change was made in the Play routes classes on 2.5.x that modified this behavior... it seems that using (prefix + "/") was not causing these issues in 2.4.x).

**Comment by kenske** [comment]
I created a new repo with only the 2.5 folder in it so it could be easily added as an sbt dependency (more instructions in the readme):

https://github.com/CreditCardsCom/swagger-play

Until this pull request makes it into master, that repository should work for everyone using Play 2.5.

**Comment by rodrigowippel** [comment]
@kenske I need help

My POST request has no body field.
I forgot something?

**Comment by kenske** [comment]
@rodrigowippel This is probably not the best place to ask for this kind of support, but if you post a question on stackoverflow I'll try to help.

**Comment by rodrigowippel** [comment]
@kenske Sorry!

**Comment by rodrigowippel** [comment]
@kenske 

Sorry!

I created a question in stackoverflow

http://stackoverflow.com/q/37616851/6381042

I'm sorry for the grammar, I'm studying English

**Comment by markusheilig** [comment]
@kenske i get the following error when i use your solution: 

conf/routes:15: type ApiHelpController is not a member of package controllers
[error] GET     /swagger.json           controllers.ApiHelpController.getResources

i created a scala-play-project with the following steps:
1. i downloaded https://github.com/CreditCardsCom/swagger-play and executed the commands
        cd swagger-play
        sbt publishLocal
2. i added   "io.swagger" %% "swagger-play2" % "1.5.2-SNAPSHOT" to my libraryDependencies
3. i added play.modules.enabled += "play.modules.swagger.SwaggerModule" to application.conf
4. i added GET  /swagger.json  controllers.ApiHelpController.getResources to the routes file

what did i do wrong?
can you please help or provide a minimalistic sample-project?
thank u very much!

EDIT: after restarting intellij idea, everything works as expected. Thank you for this fix!

**Comment by rodrigowippel** [comment]
@markusheilig 

Do you could download the dependency?
"io.swagger" %% "swagger-play 2"% "1.5.2-SNAPSHOT"
My SBT could not find.

Erro: 

`Error:Error while importing SBT project:<br/>...<br/><pre>[info] Resolving org.scoverage#scalac-scoverage-plugin_2.11;1.1.0 ...
[info] Resolving org.scala-lang#scala-compiler;2.11.7 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.4 ...
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: io.swagger#swagger-play2_2.11;1.5.2-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      io.swagger:swagger-play2_2.11:1.5.2-SNAPSHOT (C:\Repositorios\hbwatch\Backend\Play\build.sbt#L23)
[warn]        +- com.hbsis.hbwatch:common_2.11:dev
[trace] Stack trace suppressed: run 'last common/*:update' for the full output.
[trace] Stack trace suppressed: run 'last common/*:ssExtractDependencies' for the full output.
[trace] Stack trace suppressed: run 'last hbwatch-apps/*:ssExtractDependencies' for the full output.
[error] (common/*:update) sbt.ResolveException: unresolved dependency: io.swagger#swagger-play2_2.11;1.5.2-SNAPSHOT: not found
[error] (common/*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: io.swagger#swagger-play2_2.11;1.5.2-SNAPSHOT: not found
[error] (hbwatch-apps/*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: io.swagger#swagger-play2_2.11;1.5.2-SNAPSHOT: not found
[error] Total time: 11 s, completed 03/06/2016 13:39:50</pre><br/>See complete log in <a href="C:\Users\rodrigo.wippel\.IntelliJIdea2016.1\system\log\sbt.last.log">C:\Users\rodrigo.wippel\.IntelliJIdea2016.1\system\log\sbt.last.log</a>`

**Comment by markusheilig** [comment]
@rodrigowippel 
you have to compile the swagger-module yourself:
1. download source code from https://github.com/CreditCardsCom/swagger-play
2. cd swagger-play
3. sbt publishLocal

after this procedure, the module will be added to your local ivy-repository and sbt will resolve "io.swagger" %% "swagger-play 2"% "1.5.2-SNAPSHOT" successfully (by selecting your self-compiled version).

**Comment by rodrigowippel** [comment]
@markusheilig 

It works, thank you!

**Comment by rodrigowpl** [comment]
Good Morning!
Any prevision?
They need help? :)

**Comment by rodrigowippel** [comment]
@kenske Hi! Do you can help me?

http://stackoverflow.com/q/37679534/6381042

**Comment by mziemba** [comment]
Any plans on merging this PR?

**Comment by fehguy** [comment]
there's now a play-2.5 base in the project

**Pull request closed without merging**
